### ISSUE TITLE
Does not handle invalid API Key gracefully

### ISSUE THREAD

**Issue by garretthunter** [pwnraid/bnet#12]
Have been enjoying the elegance of your code. While doing some edge testing I found an issue:
...
$factory = new \Pwnraid\Bnet\ClientFactory('xyz');
$client = $factory->warcraft(new \Pwnraid\Bnet\Region(\Pwnraid\Bnet\Region::US));
$realms = $client->realms()->all();

Results in: 
Fatal error: Call to undefined method GuzzleHttp\Psr7\Response::json() in pwnraid\bnet\src\Core\AbstractClient.php on line 201

**Comment by jyggen** [comment]
Fixed in 56adc9c. Thanks for the bug report!
