### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by morloderex** [pwnraid/bnet#13]
Hello Jyggen

should we make some function to help the developer to convert for instance:  blizzard's classes and races for wow from their integer representations to their string representations. 

 And I would love to immpliment /wow/mount endpoint but where do that go under?

**Comment by jyggen** [comment]
Hi! .. and sorry for the late reply :)

I need to think about class and race functions, it _might_ be out of scope for this library.

As for /wow/mount it would probably go under `src/Warcraft/Mounts`.

**Comment by garretthunter** [comment]
@morloderex are you thinking something more than races() in Pwnraid\Bnet\Warcraft\Characters?

**Comment by morloderex** [comment]
@jyggen Should i make a PR for this or will you implement this yourself?

@garretthunter I'm thinking of mapping the entity returned from for example the the character method, so blizzards races integers could look like something like this on the entity object.

//sample data directly from the entity object returned from blizzards API before the mapping 
```json
"lastModified": 1448960961000,
    "name": "Morloderex",
    "realm": "Frostwhisper",
    "battlegroup": "Cruelty / Crueldad",
    "class": 2,
    "race": 10,
    "gender": 0,
    "level": 100,
    "achievementPoints": 5750,
    "thumbnail": "internal-record-3657/240/109304304-avatar.jpg",
    "calcClass": "b",
    "faction": 1,
    "totalHonorableKills": 5095
```

Suggested mapping example:
```json
 "lastModified": 1448960961000,
    "name": "Morloderex",
    "realm": "Frostwhisper",
    "battlegroup": "Cruelty / Crueldad",
    "class": "Paladin",
    "race": "Blood Elf",
    "gender": "Male",
    "level": 100,
    "achievementPoints": 5750,
    "thumbnail": "internal-record-3657/240/109304304-avatar.jpg",
    "calcClass": "b",
    "faction": 1,
    "totalHonorableKills": 5095
```
 
This should be able by just mapping over an array or by making a new request to blizzard via a method and then filter the necessary data.

**Comment by garretthunter** [comment]
I see, thank you for the explanation @morloderex. Because race/class data changes so rarely I am planning to cache it locally and write a library to do that transformation. I figured it would help my performance to minimize the number of calls I make to blizz api. As you noted, I will have to constantly translate all the key valuses to human friendly text.

**Comment by morloderex** [comment]
@garretthunter 
Exactly my point you got there it's meant to 
reduce the number of requests maid to the api. 

I would rather do that on the entity object if possible. 😁

**Comment by jyggen** [comment]
@morloderex Feel free to PR the mounts endpoint.

**Comment by jyggen** [comment]
@garretthunter @morloderex How about something like #14?

**Comment by garretthunter** [comment]
@jyggen yes, I like how the class / race text is now included in the character. thanks!

**Comment by morloderex** [comment]
@jyggen that's exactly what i had in mind. 

 I aplicatie that you took your time to write it out :)

**Comment by jyggen** [comment]
Cool, I'll merge it and close this issue then. Feel free to create a PR for mounts.

Thanks!
