### ISSUE TITLE
Make PSR-6 implementation optional

### ISSUE THREAD

**Issue by morloderex** [pwnraid/bnet#22]
Hello @jyggen 

I'm trying to make an adapter from Laravel cache facilities to the psr 6 interfaces. It's going great at the moment. 

My question is this: Should this package not include some kind of concrete implementation of these interfaces as per default? like you did beforehand usingtedivm/stash?

**Comment by jyggen** [comment]
Yeah, haven't decided which approach to take though. Currently I use the in-memory client from `fig/cache-util` for testing, might go for that or just write a lightweight one specifically for this package. Another idea is just make it work without a cache implementation altogether, but that requires some code changes.

**Comment by morloderex** [comment]
That last option is sounding reasonable, because i think caching is just a little bit out of scope of this package. 

Or i could be wrong here but we could just make it easy for the consumer of the package to implement caching on their own, i'm not really sure how this would work but something like the ability to make use of the package caching or to implement their own, and disable caching altogether.

**Comment by morloderex** [comment]
Any news regarding this?

**Comment by jyggen** [comment]
Yeah, I pushed a commit earlier today that should make caching optional. Let me know how if you run into any issues.

**Comment by morloderex** [comment]
Look at my comment on that commit you are referring to. 

I think we should extract the if(! $item === null) check to a readable method name. I'll make a pr for it soon.
