### ISSUE TITLE
Invalid conversion of WoW guild members to character entities

### ISSUE THREAD

**Issue by aksl** [pwnraid/bnet#28]
In **GuildEntity.php** the member-to-character conversion uses full member record (with character and rank properties) instead of character property, leading to invalid character entity (for example, $character->character['name'] instead of $character->name).

Fix should be something like this:
In line 25 of GuildEntity.php:
`$this->attributes['members'][$key]['character'] = new CharacterEntity($member);`
should be changed to:
`$this->attributes['members'][$key]['character'] = new CharacterEntity($member['character']);`

**Comment by jyggen** [comment]
Fixed in 8d3a9bf.

Thanks for reporting this!
