### ISSUE TITLE
implement the 6.0.3  changes to the bnet package

### ISSUE THREAD

**Issue by morloderex** [pwnraid/bnet#4]
### Hello @jyggen 

As of 6.0.2 (Warlords of Dreanor), the API has been updated with Item changes e.g. Item Contexts

As an example try to get the item with an ID of 113978 that will return a base site with all available contexts, but no data for that item, also new to the items while we are here, is the bl query string which indicates bonuses on the item. 

Take a look at this [link](http://us.battle.net/en/forum/topic/14927203367
) for the changes.  

Is it possible that these changes to the API can be implemented to the package @jyggen?

**Comment by jyggen** [comment]
Right, I'll take a look at it when I get the time. Thanks for reporting this! :)

**Comment by morloderex** [comment]
Any news on this?

**Comment by jyggen** [comment]
Implemented in fb77532. Sorry for the delay :)
