### ISSUE TITLE
upgrade to support Oauth2 client?

### ISSUE THREAD

**Issue by morloderex** [pwnraid/bnet#8]
Hello Pwnraid

I just wanted to make a heads up on this project, because Oauth client library has finally released a 1.x version :) 

And the tests are failing :P 

So you might want to revisit this package :)

**Comment by jyggen** [comment]
Thanks. I'll look into that.

**Comment by jyggen** [comment]
Fixed in 1f2b6f97429cd67732b833e4f5475e901e57df0b.
